spring:
  application:
    name: usermodule  # Service name for Eureka registration

  datasource:
    url: jdbc:mysql://localhost:3306/usermodule
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
server:
  port: 8081
jwt:
  secret: jwt
  expiration: 3600000
  refresh:
    expiration: 86400000

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/  # URL of the Eureka server
    fetch-registry: true
    register-with-eureka: true  # Enable Eureka client registration
  instance:
    prefer-ip-address: true  # Use IP address for registration
